id: P009286
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS20513
  title: འཇང་གླིང་གཡུལ་འགྱེད།
  author: ''
  volumes:
    d999af8ab5a84a21be687eb25e74b6ab:
      image_group_id: I8LS20515
      title: ''
      volume_number: 1
      total_pages: 340
      base_file: v001.txt
